-- units table
CREATE TABLE UNITS (
  ID                     BIGSERIAL    NOT NULL,
  CODE                   VARCHAR(4)   NOT NULL,
  LANGUAGE               VARCHAR(2)   NOT NULL DEFAULT '00',
  STICKER_STATUS         SMALLINT     NOT NULL DEFAULT 0,
  DESIGNATION            VARCHAR(128) NOT NULL,
  NAME                   VARCHAR(512),
  DESCRIPTION            VARCHAR(512),
  LABEL_DESCRIPTION      VARCHAR(512),
  LABEL_NAME             VARCHAR(128),
  LOT                    VARCHAR(4),
  SERIAL_NUMBER          VARCHAR(5),
  CREATION_DATE TIMESTAMP,
  LAST_MODIFICATION_DATE TIMESTAMP,
  PRIMARY KEY (ID)
);

-- index on designation
ALTER TABLE UNITS ADD CONSTRAINT IDX1_UNITS UNIQUE (DESIGNATION);

-- trigger on update times
CREATE TRIGGER TG1_UNITS BEFORE INSERT OR UPDATE ON UNITS FOR EACH ROW EXECUTE PROCEDURE update_times();
